services:
  - name: calendar-backend
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/event-types

  - name: calendar-frontend
    type: web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: BACKEND_SCHEME
        value: https
      - key: BACKEND_HOST
        fromService:
          name: calendar-backend
          type: web
          property: host
